/* Banco de pistas del crucigrama, escrito a mano para esta colección.
   Formato: [palabra, pista]. La palabra se muestra con tildes; el juego
   la normaliza para el tablero. Tres niveles de dificultad. */
window.PISTAS_ES = {
facil: [
["sol", "Estrella que nos alumbra de día"],
["luna", "Ilumina la noche y tiene fases"],
["casa", "Lugar donde vives"],
["gato", "Felino doméstico que ronronea"],
["perro", "El mejor amigo del hombre"],
["agua", "Sin ella no hay vida; moja"],
["fuego", "Arde y da calor"],
["mar", "Agua salada hasta el horizonte"],
["río", "Corriente de agua dulce"],
["pan", "Se hornea y acompaña la comida"],
["leche", "Blanca, sale de la vaca"],
["huevo", "Lo pone la gallina"],
["queso", "Lácteo favorito de los ratones"],
["mesa", "Mueble para comer o trabajar"],
["silla", "Mueble para sentarse"],
["cama", "Ahí duermes cada noche"],
["puerta", "Se abre para entrar"],
["ventana", "Deja pasar la luz a la casa"],
["llave", "Abre la cerradura"],
["reloj", "Marca las horas"],
["zapato", "Calzado que protege el pie"],
["camisa", "Prenda con botones y cuello"],
["sombrero", "Se lleva en la cabeza"],
["lluvia", "Agua que cae del cielo"],
["nube", "Algodón blanco en el cielo"],
["viento", "Aire en movimiento"],
["nieve", "Lluvia blanca y fría"],
["árbol", "Tiene tronco, ramas y hojas"],
["flor", "La parte más vistosa de la planta"],
["rosa", "Flor con espinas"],
["hoja", "Verde en el árbol, blanca en el cuaderno"],
["fruta", "Manzana, pera o sandía"],
["manzana", "Fruta prohibida del paraíso"],
["plátano", "Fruta amarilla y alargada"],
["naranja", "Fruta y color a la vez"],
["limón", "Cítrico muy ácido"],
["uva", "Fruta pequeña de los viñedos"],
["maíz", "Grano de las tortillas"],
["arroz", "Grano blanco, base de la paella"],
["sal", "Blanca, sazona la comida"],
["azúcar", "Endulza el café"],
["café", "Bebida oscura que despierta"],
["sopa", "Caldo que se toma con cuchara"],
["taza", "Recipiente para el café"],
["vaso", "Recipiente para beber agua"],
["plato", "Ahí se sirve la comida"],
["cuchara", "Cubierto para la sopa"],
["tenedor", "Cubierto con dientes"],
["cocina", "Cuarto donde se guisa"],
["baño", "Cuarto con regadera"],
["escuela", "Ahí van los niños a aprender"],
["maestro", "Enseña en el salón de clases"],
["libro", "Tiene páginas y se lee"],
["lápiz", "Escribe y se puede borrar"],
["papel", "Hoja para escribir"],
["carta", "Mensaje que llega en sobre"],
["número", "El dos o el siete, por ejemplo"],
["letra", "La a o la zeta, por ejemplo"],
["música", "Arte de los sonidos"],
["baile", "Movimiento al ritmo de la música"],
["fiesta", "Celebración con invitados"],
["regalo", "Se da envuelto en los cumpleaños"],
["pastel", "Dulce con velitas de cumpleaños"],
["juego", "Diversión con reglas"],
["pelota", "Esfera para jugar"],
["fútbol", "Deporte del balón y los goles"],
["gol", "Grito del estadio cuando entra el balón"],
["equipo", "Grupo que juega unido"],
["amigo", "Compañero de confianza"],
["familia", "Padres, hijos y abuelos"],
["madre", "Mujer que te dio la vida"],
["padre", "Papá"],
["hijo", "Descendiente directo"],
["abuelo", "El papá de tu papá"],
["niño", "Persona de pocos años"],
["mano", "Tiene cinco dedos"],
["dedo", "Diez en las manos"],
["ojo", "Órgano de la vista"],
["boca", "Con ella hablas y comes"],
["nariz", "Órgano del olfato"],
["oreja", "A los lados de la cabeza"],
["diente", "Blanco, muerde en la boca"],
["pelo", "Crece en la cabeza"],
["cabeza", "Parte superior del cuerpo"],
["corazón", "Late en el pecho"],
["sangre", "Líquido rojo del cuerpo"],
["médico", "Cura a los enfermos"],
["caballo", "Se monta y relincha"],
["vaca", "Da leche y muge"],
["pollo", "Cría de la gallina"],
["pez", "Vive en el agua y nada"],
["pájaro", "Vuela y hace nidos"],
["león", "Rey de la selva"],
["mono", "Animal que trepa y hace gracias"],
["oso", "Grande y peludo, duerme en invierno"],
["ratón", "Roedor pequeño que teme al gato"],
["abeja", "Hace miel en el panal"],
["hormiga", "Pequeña y muy trabajadora"],
["araña", "Teje telarañas"],
["tortuga", "Lenta y con caparazón"],
["ciudad", "Muchas calles y edificios"],
["pueblo", "Población pequeña"],
["calle", "Por ella pasan los coches"],
["coche", "Vehículo de cuatro ruedas"],
["camión", "Vehículo grande de carga"],
["tren", "Corre sobre rieles"],
["avión", "Vuela entre ciudades"],
["barco", "Navega por el mar"],
["puente", "Cruza el río por arriba"],
["camino", "Por él se llega a los lugares"],
["playa", "Arena junto al mar"],
["montaña", "Elevación grande de tierra"],
["campo", "Tierra fuera de la ciudad"],
["piedra", "Dura, está en el suelo"],
["arena", "Granitos de la playa"],
["oro", "Metal precioso amarillo"],
["plata", "Metal precioso blanco"],
["dinero", "Con él se paga"],
["tienda", "Ahí se compra de todo"],
["trabajo", "Actividad que da un sueldo"],
["día", "Del amanecer al anochecer"],
["noche", "Cuando sale la luna"],
["año", "Doce meses"],
["mes", "Enero o abril, por ejemplo"],
["hora", "Sesenta minutos"],
["verano", "Estación más calurosa"],
["invierno", "Estación más fría"],
["color", "Rojo, verde o azul"],
["blanco", "Color de la nieve"],
["negro", "Color de la noche"],
["rojo", "Color de la sangre"],
["verde", "Color de las plantas"],
["azul", "Color del cielo despejado"],
],
media: [
["ancla", "Sujeta el barco al fondo"],
["brújula", "Siempre apunta al norte"],
["faro", "Torre con luz que guía barcos"],
["isla", "Tierra rodeada de agua"],
["puerto", "Ahí atracan los barcos"],
["marea", "Sube y baja con la luna"],
["ola", "El mar la revienta en la playa"],
["velero", "Barco empujado por el viento"],
["timón", "Con él se dirige el barco"],
["desierto", "Arena, dunas y poca lluvia"],
["oasis", "Agua y palmeras en el desierto"],
["selva", "Bosque tropical muy tupido"],
["volcán", "Montaña que escupe lava"],
["lava", "Roca fundida del volcán"],
["cueva", "Hueco natural en la roca"],
["cumbre", "Punto más alto de la montaña"],
["valle", "Llanura entre montañas"],
["orilla", "Borde del río o del mar"],
["niebla", "Nube a ras de suelo"],
["trueno", "Ruido que sigue al rayo"],
["rayo", "Descarga eléctrica del cielo"],
["arcoíris", "Puente de colores tras la lluvia"],
["sombra", "Te sigue en los días de sol"],
["eco", "Repite lo que gritas en la montaña"],
["huella", "Marca que deja el pie"],
["semilla", "De ella nace la planta"],
["raíz", "Parte enterrada de la planta"],
["cosecha", "Frutos que se recogen del campo"],
["trigo", "Cereal del pan"],
["molino", "Muele grano con aspas"],
["granja", "Casa de campo con animales"],
["establo", "Casa de las vacas"],
["colmena", "Casa de las abejas"],
["nido", "Cuna de los pájaros"],
["jaula", "Encierro con barrotes"],
["búho", "Ave nocturna que ulula"],
["águila", "Ave rapaz de vista aguda"],
["cuervo", "Ave negra de mal agüero"],
["ballena", "El animal más grande del mar"],
["delfín", "Cetáceo listo y juguetón"],
["tiburón", "Pez temido de gran aleta"],
["pulpo", "Ocho brazos en el mar"],
["cangrejo", "Camina de lado con pinzas"],
["caracol", "Lleva su casa a cuestas"],
["culebra", "Reptil que repta sin patas"],
["lagarto", "Reptil que toma el sol"],
["camello", "Cruza el desierto con jorobas"],
["zorro", "Astuto de cola peluda"],
["lobo", "Aúlla a la luna en manada"],
["ciervo", "Luce cornamenta en el bosque"],
["ardilla", "Guarda nueces en el árbol"],
["murciélago", "Mamífero que vuela de noche"],
["disfraz", "Ropa para no ser reconocido"],
["máscara", "Cubre la cara en el carnaval"],
["teatro", "Escenario, telón y aplausos"],
["función", "Cada pase de la obra"],
["orquesta", "Muchos músicos tocando juntos"],
["violín", "Instrumento de cuerda y arco"],
["tambor", "Se toca con baquetas"],
["flauta", "Instrumento de viento con agujeros"],
["guitarra", "Seis cuerdas para rasguear"],
["piano", "Teclas blancas y negras"],
["trompeta", "Metal que suena en la banda"],
["poema", "Versos con ritmo"],
["novela", "Libro largo de ficción"],
["cuento", "Relato corto para dormir"],
["leyenda", "Historia antigua entre real y mágica"],
["museo", "Guarda obras de arte"],
["estatua", "Figura esculpida en piedra o bronce"],
["retrato", "Pintura de una persona"],
["pincel", "Herramienta del pintor"],
["lienzo", "Tela donde se pinta"],
["mapa", "Dibujo de países y caminos"],
["frontera", "Línea que separa dos países"],
["bandera", "Tela con los colores de un país"],
["moneda", "Dinero metálico"],
["billete", "Dinero de papel"],
["mercado", "Puestos, regateo y fruta fresca"],
["cosquillas", "Roce que provoca risa"],
["estornudo", "¡Salud! después de él"],
["bostezo", "Se contagia cuando hay sueño"],
["susurro", "Voz muy bajita al oído"],
["silbido", "Música con los labios"],
["carcajada", "Risa fuerte y abierta"],
["destino", "Lo que el futuro depara"],
["memoria", "Con ella se recuerda"],
["olvido", "Lo contrario del recuerdo"],
["sueño", "Historia que ves al dormir"],
["pesadilla", "Sueño que asusta"],
["madrugada", "Horas antes del amanecer"],
["atardecer", "Cuando el sol se despide"],
["horizonte", "Línea donde cielo y mar se juntan"],
["equipaje", "Maletas del viajero"],
["pasaporte", "Documento para cruzar fronteras"],
["brindis", "Choque de copas y buenos deseos"],
["receta", "Instrucciones del cocinero"],
["harina", "Polvo blanco del panadero"],
["levadura", "Hace crecer la masa"],
["mermelada", "Fruta convertida en dulce untable"],
["vinagre", "Ácido que adereza la ensalada"],
["canela", "Especia en rama o en polvo"],
["hierbabuena", "Hoja fresca del mojito y el té"],
["ajedrez", "Juego de reyes, torres y alfiles"],
["dominó", "Fichas blancas con puntos negros"],
["lotería", "Juego de azar con cartones"],
["columpio", "Sube y baja colgado de cadenas"],
["cometa", "Vuela con hilo en el parque"],
["trompo", "Juguete que gira sobre su punta"],
["títere", "Muñeco movido con la mano"],
["martillo", "Golpea los clavos"],
["clavo", "Se hunde a martillazos"],
["tornillo", "Se aprieta con desarmador"],
["serrucho", "Corta madera con dientes"],
["escalera", "Sirve para subir peldaño a peldaño"],
["andamio", "Estructura para obreros en altura"],
["cimiento", "Base enterrada del edificio"],
["azotea", "Techo plano para tender ropa"],
["chimenea", "Por ella sale el humo"],
["balcón", "Asomadero con barandal"],
["pasillo", "Corredor entre cuartos"],
["sótano", "Cuarto bajo el nivel del suelo"],
["desván", "Cuarto de los trebejos, arriba"],
["candado", "Cierra con llave la reja"],
["cerrojo", "Asegura la puerta por dentro"],
["bisagra", "Permite girar la puerta"],
["cortina", "Tela que tapa la ventana"],
["alfombra", "Tapete grande del salón"],
["almohada", "Cojín para la cabeza"],
["cobija", "Abriga en la cama"],
["espejo", "Devuelve tu imagen"],
["peine", "Ordena el cabello"],
["tijeras", "Dos hojas que cortan"],
["aguja", "Fina, con ojo para el hilo"],
["hilo", "Pasa por el ojo de la aguja"],
["botón", "Cierra la camisa"],
["bolsillo", "Guarda cosas en el pantalón"],
["cinturón", "Sujeta el pantalón"],
["bufanda", "Abriga el cuello en invierno"],
["guante", "Viste la mano"],
["paraguas", "Techo portátil contra la lluvia"],
],
dificil: [
["albatros", "Ave marina de alas enormes"],
["colibrí", "Ave diminuta que aletea sin parar"],
["ornitorrinco", "Mamífero con pico de pato"],
["camaleón", "Cambia de color a voluntad"],
["escarabajo", "Insecto de caparazón duro"],
["luciérnaga", "Insecto con farol propio"],
["medusa", "Gelatina flotante que pica"],
["coral", "Animal marino que parece piedra"],
["anguila", "Pez alargado, a veces eléctrico"],
["esturión", "Pez del que sale el caviar"],
["archipiélago", "Conjunto de islas"],
["península", "Tierra casi rodeada de agua"],
["estrecho", "Paso angosto entre dos mares"],
["afluente", "Río que desemboca en otro río"],
["delta", "Desembocadura en forma de abanico"],
["meandro", "Curva pronunciada de un río"],
["glaciar", "Río de hielo que avanza lento"],
["géiser", "Chorro de agua caliente que brota"],
["estalactita", "Cuelga del techo de la cueva"],
["duna", "Colina de arena que camina"],
["equinoccio", "Día y noche duran lo mismo"],
["solsticio", "Día más largo o más corto del año"],
["eclipse", "Un astro tapa a otro"],
["constelación", "Dibujo de estrellas en el cielo"],
["nebulosa", "Nube cósmica donde nacen estrellas"],
["meteorito", "Piedra del espacio que cae a tierra"],
["órbita", "Camino de un planeta alrededor del sol"],
["gravedad", "Fuerza que todo lo atrae al suelo"],
["péndulo", "Oscila colgado en el reloj de pared"],
["polea", "Rueda que ayuda a levantar peso"],
["palanca", "Con un punto de apoyo mueve el mundo"],
["engranaje", "Rueda dentada que gira con otra"],
["brújula", "Aguja imantada del explorador"],
["astrolabio", "Antiguo instrumento de navegantes"],
["telescopio", "Acerca las estrellas al ojo"],
["microscopio", "Agranda lo invisible"],
["alambique", "Aparato para destilar"],
["imán", "Atrae al hierro sin tocarlo"],
["azogue", "Nombre antiguo del mercurio"],
["ámbar", "Resina fósil dorada"],
["obsidiana", "Vidrio volcánico negro"],
["cuarzo", "Cristal muy común y muy duro"],
["esmeralda", "Gema verde por excelencia"],
["zafiro", "Gema azul hermana del rubí"],
["alquimia", "Química medieval que buscaba oro"],
["jeroglífico", "Escritura de los faraones"],
["papiro", "Papel del antiguo Egipto"],
["pergamino", "Piel preparada para escribir"],
["manuscrito", "Texto escrito a mano"],
["códice", "Libro antiguo, tesoro de biblioteca"],
["imprenta", "Invento de Gutenberg"],
["alfabeto", "Todas las letras en orden"],
["acertijo", "Pregunta con trampa para pensar"],
["paradoja", "Verdad que parece contradicción"],
["metáfora", "Decir una cosa nombrando otra"],
["soneto", "Poema de catorce versos"],
["epopeya", "Poema épico de héroes"],
["laberinto", "Fácil entrar, difícil salir"],
["minotauro", "Toro y hombre en el laberinto"],
["esfinge", "Preguntaba enigmas en Egipto y Tebas"],
["fénix", "Ave que renace de sus cenizas"],
["dragón", "Reptil alado que escupe fuego"],
["unicornio", "Caballo con un cuerno"],
["sirena", "Canto peligroso en alta mar"],
["centinela", "Vigila de guardia en la muralla"],
["catapulta", "Lanzaba piedras al castillo"],
["armadura", "Traje metálico del caballero"],
["escudo", "Protege del golpe enemigo"],
["ballesta", "Arco mecánico medieval"],
["muralla", "Muro que rodea la ciudad antigua"],
["acueducto", "Puente que lleva agua"],
["anfiteatro", "Arena romana de gladiadores"],
["obelisco", "Aguja de piedra egipcia"],
["pirámide", "Tumba monumental de faraones"],
["catacumba", "Cementerio subterráneo"],
["claustro", "Patio interior del convento"],
["vitral", "Ventana de colores en la catedral"],
["gárgola", "Monstruo de piedra que escupe lluvia"],
["andén", "Espera del tren junto a la vía"],
["semáforo", "Ordena el tráfico con tres luces"],
["periscopio", "Ojo del submarino"],
["dirigible", "Globo alargado con motor"],
["catalejo", "Telescopio de bolsillo pirata"],
["sextante", "Medía la altura de los astros a bordo"],
["vendaval", "Viento muy fuerte"],
["ventisca", "Nieve con viento furioso"],
["aurora", "Luces del cielo polar"],
["crepúsculo", "Luz tenue entre día y noche"],
["penumbra", "Ni luz ni oscuridad total"],
["silueta", "Contorno oscuro de una figura"],
["reflejo", "La luna lo deja en el lago"],
["espejismo", "Agua que no existe en el desierto"],
["vértigo", "Mareo de las alturas"],
["insomnio", "Noche entera sin poder dormir"],
["nostalgia", "Extrañar lo que ya pasó"],
["melancolía", "Tristeza suave y sin motivo"],
["euforia", "Alegría desbordada"],
["elocuencia", "Arte de hablar convenciendo"],
["astucia", "Ingenio del zorro"],
["osadía", "Atrevimiento sin miedo"],
["hazaña", "Logro heroico"],
["utopía", "Mundo perfecto imposible"],
["quimera", "Ilusión imposible; monstruo mitológico"],
["vestigio", "Huella de algo que ya no está"],
["reliquia", "Objeto sagrado muy antiguo"],
["talismán", "Objeto de la buena suerte"],
["amuleto", "Se lleva encima contra el mal"],
["horóscopo", "Predicción según tu signo"],
["oráculo", "Respondía el futuro en Delfos"],
["clepsidra", "Reloj de agua"],
["efímero", "Dura un instante y se va"],
["perenne", "Que no se marchita nunca"],
["azar", "Suerte pura, sin plan"],
["enigma", "Misterio por resolver"],
]
};
