const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {webcrypto}=require('node:crypto');
const code=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').split('<script>')[1].split('</script>')[0];
function app(initial){
  const data=new Map(initial?[['reparte.v1',JSON.stringify(initial)]]:[]), handlers={};
  const element={content:'',innerHTML:'',setAttribute(){},remove(){},click(){}};
  const context=vm.createContext({console,structuredClone,crypto:webcrypto,TextEncoder,TextDecoder,URL,Blob,AbortSignal,Response,CompressionStream:undefined,DecompressionStream:undefined,
    btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),
    localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},
    document:{querySelector:s=>s==='#app'?element:null,createElement:()=>({...element}),body:{appendChild(){}},addEventListener:(n,fn)=>(handlers[n]??=[]).push(fn),activeElement:null},
    location:{hash:'#/',href:'https://reparte.test/',protocol:'https:'},navigator:{onLine:true},
    window:{addEventListener(){}},setTimeout:()=>1,clearTimeout(){},setInterval(){},confirm:()=>true,fetch:()=>{throw Error('Unexpected fetch');}});
  context.self=context;
  vm.runInContext(code,context);
  return {run:s=>vm.runInContext(s,context),data,context,handlers};
}
const sample=()=>({id:'trip',name:'Ensayo',createdAt:'2026-09-23',role:'owner',organizerId:'ana',meId:'ana',fx:18.4,closed:false,members:['ana','beto','carla','diego'].map(id=>({id,name:id,clabe:'012345678901234567'})),expenses:[{id:'dinner',title:'Cena',amt:120000,cur:'MXN',fx:18.4,payerId:'ana',among:['ana','beto','carla','diego'],date:'2026-09-23',history:[]},{id:'taxi',title:'Taxi',amt:2000,cur:'USD',fx:18,payerId:'beto',among:['beto','carla'],date:'2026-09-23',history:[]}],payments:[]});
function fixture(){const a=app();a.context.ev=sample();a.run('db.events[ev.id]=ev');return a;}
test('four-person account and subgroup shares balance exactly',()=>{const a=fixture();assert.deepEqual(JSON.parse(a.run('JSON.stringify(balances(ev))')),{ana:90000,beto:-12000,carla:-48000,diego:-30000});assert.equal(a.run('personTotals(ev,"carla").share'),48000);});
test('odd cent and payer outside subgroup preserve cents',()=>{const a=fixture();assert.equal(a.run('Object.values(shares({...ev.expenses[0],amt:100,among:["beto","carla","diego"]})).reduce((a,b)=>a+b,0)'),100);});
test('all transfers settle outstanding balances after mixed partial payments',()=>{const a=fixture();a.run('ev.payments=[{from:"carla",to:"ana",amt:10000},{from:"beto",to:"diego",amt:2000},{from:"diego",to:"ana",amt:40000}]');assert.equal(a.run('Object.values(balancesFrom(ev,[...ev.payments,...transfers(ev)])).every(v=>v===0)'),true);});
test('partial payments retain the original destination when possible',()=>{const a=fixture();a.run('ev.payments=[{from:"carla",to:"ana",amt:10000}]');assert.equal(a.run('transfers(ev).find(t=>t.from==="carla").amt'),38000);assert.equal(a.run('transfers(ev).find(t=>t.from==="carla").paid'),10000);});
test('payment confirmation requires organizer and closed event',()=>{const a=fixture();a.run('markPaid(ev,0)');assert.equal(a.run('ev.payments.length'),0);a.run('ev.closed=true;ev.role="viewer";markPaid(ev,0)');assert.equal(a.run('ev.payments.length'),0);a.run('ev.role="owner";markPaid(ev,0)');assert.equal(a.run('ev.payments.length'),1);});
test('negative and nonfinite payments rejected',()=>{const a=fixture();a.run('ev.closed=true;markPaid(ev,0,-2);markPaid(ev,0,Infinity)');assert.equal(a.run('ev.payments.length'),0);});
test('shared copy excludes bank details, ownership, and cloud credentials',async()=>{const a=fixture();a.run('ev.sync={ownerId:"secret",token:"private-token"};ev.password="secret"');const s=await a.run('encodeEvent(ev)');a.context.shared=s;const decoded=await a.run('decodeEvent(shared)');assert.equal(decoded.role,undefined);assert.equal(decoded.sync,undefined);assert.equal(decoded.members[0].clabe,undefined);assert.equal(decoded.password,undefined);});
test('malicious shared link cannot overwrite an owned account',()=>{const a=fixture();a.run('const evil=structuredClone(ev);evil.expenses[0].amt=999;importEvent(evil)');assert.equal(a.run('db.events.trip.expenses[0].amt'),120000);});
test('imported ownership and session metadata are ignored',()=>{const a=fixture();a.run('delete db.events.trip; ev.sync={ownerId:"injected"};importEvent(ev)');assert.equal(a.run('db.events.trip.role'),'viewer');assert.equal(a.run('db.events.trip.sync'),undefined);assert.equal(a.run('db.events.trip.members[0].clabe'),undefined);});
test('selecting someone does not grant management rights',()=>{const a=fixture();a.run('ev.role="viewer";ev.meId=ev.organizerId');assert.equal(a.run('canManage(ev)'),false);assert.doesNotMatch(a.run('eventScreen(ev)'),/data-act="capture"/);});
test('rejects missing, duplicated, and invalid participant data',()=>{for(const mutation of ['ev.members=[]','ev.members[0].id="bad\\\" onclick=oops"','ev.expenses[0].among=["nobody"]','ev.expenses[0].among=["ana","ana"]','ev.expenses[0].amt=-1','ev.expenses[0].fx=Infinity','ev.expenses[0].date="not-a-date"']){const a=fixture();a.run(mutation);assert.throws(()=>a.run('validateEvent(ev)'));}});
test('closing first and subsequent events never adds a fee',async()=>{const a=fixture();a.run('route={id:"trip",screen:"cierre"};ui.sheet={type:"close"}');assert.match(a.run('sheet(ev)'),/Cerrar sin costo/);for(let n=0;n<2;n++){const target={dataset:{act:'confirm-close'},closest(){return this}};await a.handlers.click[0]({target});assert.equal(a.run('ev.expenses.length'),2);assert.equal(a.run('ev.fee'),null);a.run('ev.closed=false');}});
test('legacy synthetic fee is removed only after recovery copy is saved',()=>{const ev=sample();ev.expenses.push({id:'fee',isFee:true,history:['Cuota del evento, repartida entre todos'],amt:4900});ev.fee=4900;const a=app({events:{trip:ev},profile:{name:'ana'}});assert.equal(a.run('db.events.trip.expenses.length'),2);assert.match(a.data.get('reparte.before-fee-fix'),/4900/);});
test('conflict disables editing and foreign cloud owner cannot manage',()=>{const a=fixture();a.run('ev.sync={conflict:true}');assert.equal(a.run('guard(ev)'),false);a.run('ev.sync={ownerId:"other-user"}');assert.equal(a.run('canManage(ev)'),false);});
test('backup restoration validates the entire backup before adding any event',async()=>{const a=fixture();a.context.file={size:10,text:async()=>JSON.stringify({format:'reparte-backup-v2',events:{bad:{id:'bad'}}})};await assert.rejects(a.run('restoreBackup(file)'));assert.equal(a.run('Object.keys(db.events).length'),1);});
test('cloud conflict preserves local edits',async()=>{const a=fixture();a.run('cloud.url="https://project.supabase.co";cloud.key="public";cloud.session={access_token:"test",expires_at:9999999999,user:{id:"owner"}};ev.sync={ownerId:"owner",version:1,last:JSON.stringify(publicEvent(ev))};ev.name="Local changes"');const row={id:'trip',owner_id:'owner',version:2,view_token:'11111111-1111-4111-8111-111111111111',snapshot:sample()};a.context.fetch=async()=>({ok:true,json:async()=>[row]});await a.run('syncAll()');assert.equal(a.run('ev.sync.conflict'),true);assert.equal(a.run('db.events.trip.name'),'Local changes');});
test('cloud recovery restores owner by authenticated server response',async()=>{const a=app();a.run('cloud.url="https://project.supabase.co";cloud.key="public";cloud.session={access_token:"test",expires_at:9999999999,user:{id:"owner"}}');const row={id:'trip',owner_id:'owner',version:2,view_token:'11111111-1111-4111-8111-111111111111',snapshot:sample()};a.context.fetch=async()=>({ok:true,json:async()=>[row]});await a.run('syncAll()');assert.equal(a.run('canManage(db.events.trip)'),true);assert.equal(a.run('db.events.trip.members[0].clabe'),undefined);});
test('cloud upload records sent baseline, preserving edits made during request',async()=>{const a=fixture();a.run('cloud.url="https://project.supabase.co";cloud.key="public";cloud.session={access_token:"test",expires_at:9999999999,user:{id:"owner"}}');a.context.fetch=async url=>{if(url.includes('/rpc/')){a.run('ev.name="Changed during upload"');return {ok:true,json:async()=>({version:1,view_token:'token'})};}return {ok:true,json:async()=>[]};};await a.run('syncAll()');assert.equal(a.run('ev.name'),'Changed during upload');assert.notEqual(a.run('ev.sync.last'),a.run('JSON.stringify(publicEvent(ev))'));});
test('undo cannot change expenses after the event was closed',()=>{const a=fixture();a.run('ui.cap={editId:"dinner",amount:"100",cur:"MXN",fx:18,payerId:"ana",among:["ana","beto","carla","diego"],date:"2026-09-23",title:"Corrected"};saveCapture(ev);ev.closed=true;undoFn()');assert.equal(a.run('ev.expenses[0].amt'),10000);});
test('service worker upgrade preserves caches belonging to sibling apps',async()=>{const handlers={},deleted=[];const worker=fs.readFileSync(require('node:path').join(__dirname,'../sw.js'),'utf8');vm.runInNewContext(worker,{self:{addEventListener:(n,fn)=>handlers[n]=fn,clients:{claim:async()=>{}}},caches:{keys:async()=>['sobremesa-v7','reparte-v1','reparte-v2'],delete:async k=>deleted.push(k)}});let completion;handlers.activate({waitUntil:p=>completion=p});await completion;assert.deepEqual(deleted,['reparte-v1']);});
