const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,...(process.env.REPARTE_BROWSER?{executablePath:process.env.REPARTE_BROWSER}:{})});
  const owner=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});
  const page=await owner.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765');
  await page.getByRole('button',{name:'+ Nuevo evento',exact:true}).click();
  await page.locator('input[name=name]').fill('Ensayo de cuatro');
  await page.locator('input[name=me]').fill('Ana');
  await page.getByRole('button',{name:'Crear evento',exact:true}).click();
  for(const name of ['Beto','Carla','Diego']){
    await page.getByRole('button',{name:'+ Agregar',exact:true}).click();
    await page.locator('#f-member input').fill(name);
    await page.locator('#f-member button').click();
  }
  await page.getByRole('button',{name:'+ Gasto',exact:true}).click();
  for(const key of '1200') await page.locator(`[data-key="${key}"]`).click();
  await page.locator('[data-title]').fill('Cena de todos');
  await page.locator('[data-act=save-cap]').click();
  await page.getByRole('button',{name:'+ Gasto',exact:true}).click();
  await page.locator('[data-cur=USD]').click();
  for(const key of '20') await page.locator(`[data-key="${key}"]`).click();
  await page.locator('[data-act=edit-fx]').click();
  await page.locator('input[name=fx]').fill('18');
  await page.locator('#f-fx button').click();
  await page.locator('[data-title]').fill('Taxi Beto y Carla');
  await page.locator('[data-act=toggle-split]').click();
  await page.locator('[data-payer]').filter({hasText:'Beto'}).click();
  await page.locator('[data-among]').filter({hasText:'Tú'}).click();
  await page.locator('[data-among]').filter({hasText:'Diego'}).click();
  await page.locator('[data-act=save-cap]').click();
  await page.getByRole('button',{name:'Cerrar evento',exact:true}).click();
  await page.getByText('Lo que le toca a cada quien',{exact:true}).waitFor();
  await page.screenshot({path:'/tmp/reparte-cierre.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Cerrar evento y ver resumen',exact:true}).click();
  await page.getByRole('button',{name:'Cerrar sin costo',exact:true}).click();
  let event=await page.evaluate(()=>Object.values(db.events)[0]);
  assert.equal(event.expenses.length,2);assert.equal(event.fee,null);
  await page.getByRole('button',{name:'‹ Liquidación',exact:true}).click();
  await page.locator('[data-pay]').first().click();
  await page.getByRole('button',{name:'Confirmar una parte…',exact:true}).click();
  await page.locator('input[name=amt]').fill('100');
  await page.locator('#f-partial button').click();
  event=await page.evaluate(()=>Object.values(db.events)[0]);assert.equal(event.payments[0].amt,10000);
  await page.getByRole('button',{name:'‹ Gastos',exact:true}).click();
  await page.getByRole('button',{name:'⌗ Invitar',exact:true}).click();
  await page.getByRole('button',{name:'Copiar',exact:true}).waitFor();
  const shared=await page.evaluate(async()=>{const ev=Object.values(db.events)[0];return location.origin+'/#e='+await encodeEvent(ev)});
  const reader=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});
  const view=await reader.newPage(); view.on('pageerror',e=>errors.push(e.message));
  await view.goto(shared);
  await view.getByRole('heading',{name:'Ensayo de cuatro',exact:true}).waitFor();
  assert.equal(await view.locator('[data-act=capture]').count(),0);
  await view.locator('[data-act=view-person]').click();
  await view.getByRole('button',{name:'Carla',exact:true}).click();
  await view.getByText('Debes',{exact:true}).waitFor();
  await view.locator('[data-exp]').filter({hasText:'Taxi Beto y Carla'}).click();
  await view.getByRole('heading',{name:'Taxi Beto y Carla',exact:true}).waitFor();
  await view.screenshot({path:'/tmp/reparte-consulta.png',fullPage:true,animations:'disabled'});
  assert.equal(await view.locator('[data-act=save-cap]').count(),0);
  assert.deepEqual(errors,[]);
  assert.equal(await view.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  // Download and restore in a clean device, including validation through the actual file input.
  await page.goto('http://127.0.0.1:8765/#/conectar');
  const downloadPromise=page.waitForEvent('download');await page.locator('[data-act=backup]').click();
  const download=await downloadPromise;await download.saveAs('/tmp/reparte-browser-backup.json');
  const recovery=await browser.newContext({serviceWorkers:'block'});const recovered=await recovery.newPage();
  await recovered.goto('http://127.0.0.1:8765/#/conectar');await recovered.locator('#restore-file').setInputFiles('/tmp/reparte-browser-backup.json');
  await recovered.getByText('Respaldo restaurado.',{exact:true}).waitFor();
  const recoveredCount=await recovered.evaluate(()=>Object.values(db.events)[0].expenses.length);assert.equal(recoveredCount,2);
  console.log('PASS: four-person browser flow, MXN/USD subgroup, free closure, partial payment, independent read-only device, expense breakdown, backup recovery, mobile width, no JS errors');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
